FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install 


RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .  

CMD ["npm", "run", "start"]

# docker run -p 3000:3000 ad71d35f5702